stages:
  - test
  - lint

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  UV_CACHE_DIR: "$CI_PROJECT_DIR/.cache/uv"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/pip
    - .cache/uv
    - .venv

.python_base:
  image: registry.access.redhat.com/ubi9/python-311:latest
  tags:
    - aipcc-k8s-cicd
  before_script:
    - pip install --upgrade pip
    - pip install uv
    - uv sync

test:
  extends: .python_base
  stage: test
  script:
    - uv run pytest -v --tb=short
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'

lint:format:
  extends: .python_base
  stage: lint
  script:
    - uv run ruff format --check .
  allow_failure: false

lint:check:
  extends: .python_base
  stage: lint
  script:
    - uv run ruff check .
  allow_failure: false