definitions:
  - application: base-images
    tenant: ai-tenant
    branch: main
    components:
      - name: base-image-cpu
        context: .
        dockerfile: Containerfile.cpu-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/cpu
        pipelinerun:
          - build_args_file: build-args/cpu-app.conf
            pipeline: full-container
            variant: cpu
            build_platforms:
              - linux/arm64
              - linux/ppc64le
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-cuda
        context: .
        dockerfile: Containerfile.cuda-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/cuda
        pipelinerun:
          - build_args_file: build-args/cuda-app.conf
            pipeline: full-container
            variant: cuda
            build_platforms:
              - linux/arm64
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-cuda-12-9
        context: .
        dockerfile: Containerfile.cuda-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/cuda-12.9-el9.6
        pipelinerun:
          - build_args_file: build-args/cuda12.9-el9.6-app.conf
            pipeline: full-container
            variant: cuda
            build_platforms:
              - linux/arm64
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-cuda-12-8
        context: .
        dockerfile: Containerfile.cuda-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/cuda-12.8-el9.6
        pipelinerun:
          - build_args_file: build-args/cuda12.8-el9.6-app.conf
            pipeline: full-container
            variant: cuda
            build_platforms:
              - linux/arm64
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-gaudi
        context: .
        dockerfile: Containerfile.gaudi-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/gaudi
        pipelinerun:
          - build_args_file: build-args/gaudi-app.conf
            pipeline: full-container
            variant: gaudi
            build_platforms:
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-rocm
        context: .
        dockerfile: Containerfile.rocm-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/rocm
        pipelinerun:
          - build_args_file: build-args/rocm-app.conf
            pipeline: full-container
            variant: rocm
            build_platforms:
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-spyre
        context: ./context/
        dockerfile: Containerfile.spyre-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/spyre
        pipelinerun:
          - build_args_file: build-args/spyre-app.conf
            pipeline: full-container
            variant: spyre
            build_platforms:
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
      - name: base-image-tpu
        context: .
        dockerfile: Containerfile.tpu-app
        url: https://gitlab.com/redhat/rhel-ai/core/base-images/app
        stage_repository: quay.io/aipcc/base-images/tpu
        pipelinerun:
          - build_args_file: build-args/tpu-app.conf
            pipeline: full-container
            variant: tpu
            build_platforms:
              - linux/x86_64
            additional_build_secret: global-pull-secret
            skip-checks: false
            timeouts:
              pipeline: "4h0m0s"
    release_plan:
      - name: base-images-stage
        grace_period: 30
        autorelease: true
    release_plan_admission:
      - name: base-images-stage
        policy: registry-ai-quay-stage
        single_component_mode: true
        tags:
          - "latest"
          - "3.0"
          - "3.0-{{ timestamp }}"
        product_name: Red Hat AI Inference Server
        product_version: "3.1"
        product_id: [ 1001 ]
        intention: staging
        service_account: release-registry-rhelai
        pipeline_path: pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
