definitions:
  - application: llama-stack
    tenant: ai-tenant
    branch: rhoai-2.23
    components:
      - name: llama-stack-cpu
        context: .
        dockerfile: Containerfile.cpu-ubi9
        url: https://gitlab.com/redhat/rhel-ai/llama-stack/containers
        repository: quay.io/aipcc/llama-stack/cpu-ubi9
        pipelinerun:
          - build_args_file: build-args/cpu-ubi9.conf
            pipeline: full-container
            variant: spyre
            build_platforms:
              - linux/x86_64
              - linux-d160-m2xlarge/arm64
            additional_build_secret: rhel-ai-private-index-auth
            skip-checks: true
            timeouts:
              pipeline: "4h0m0s"
    release_plan:
      - name: llama-stack-stage
        grace_period: 30
        autorelease: true
    release_plan_admission:
      - name: llama-stack-stage
        policy: registry-ai-quay-stage
        single_component_mode: true
        tags:
          - "rhoai-2.23"
          - "rhoai-2.23-{{ timestamp }}"
        product_name: Red Hat AI Inference Server
        product_version: "3.1"
        product_id: [ 1001 ]
        intention: staging
