definitions:
  - application: rhelai-bootc
    tenant: rhel-ai-tenant
    branch: "3.0"
    components:
      - name: bootc-cuda-disk-image-container
        context: .
        dockerfile: Containerfile.bootc-cuda-disk-image-container
        url: https://gitlab.com/redhat/rhel-ai/containers/bootc
        stage_repository: quay.io/aipcc/rhelai3/bootc-cuda-disk-image-container-rhel9
        prod_repository: registry.redhat.io/rhelai3/disk-image-nvidia-rhel9
        pipelinerun:
          - pipeline: full-container
            path_context: "."
            build_args_file: argfile-bootc-cuda-disk-image-container.conf
            additional_build_secret: bootc-cuda-qcow2-disk-image-image-pull
            snyk_project_name: ai-red-hat-enterprise-linux-ai
            snyk_org: 01db29d0-f8e7-4709-9725-442d48ddfba6
            timeouts:
              pipeline: "24h0m0s"
              tasks: "6h0m0s"
              finally: "6h0m0s"

    release_plan:
      - name: bootc-disk-image-containers-stage
        grace_period: 30
        autorelease: true
      - name: bootc-disk-image-containers-prod
        grace_period: 30
        autorelease: false

    release_plan_admission:
      - name: bootc-disk-image-containers-stage
        policy: registry-rhel-ai-disk-image-containers-stage
        integration_test_scenario:
          enabled: true
          optional: true
          timeout: 40m0s
          single_component: true
        single_component_mode: true
        service_account: release-registry-rhelai
        pipeline_path: pipelines/managed/push-to-external-registry/push-to-external-registry.yaml
        tags:
          - "3.0.0"
          - "3.0"
          - "3.0.0-{{ timestamp }}"
          - "latest"
        product_name: Red Hat Enterprise Linux AI
        product_version: "3.0"
        product_id: [ 932 ]
        intention: staging
      - name: bootc-disk-image-containers-prod
        policy: registry-rhel-ai-disk-image-containers-prod
        single_component_mode: true
        service_account: release-registry-prod
        pipeline_path: pipelines/managed/rh-advisories/rh-advisories.yaml
        tags:
          - "3.0.0"
          - "3.0"
          - "3.0.0-{{ timestamp }}"
          - "latest"
        product_name: Red Hat Enterprise Linux AI
        product_version: "3.0"
        product_id: [ 932 ]
        intention: production
