#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<EOF
Usage: $(basename "$0") --configs-dir <path> --krd-repo <path> [--product <name>] [--all]

Compare PMT-generated KRD output against an actual KRD repo to detect drift.

Options:
  --configs-dir   Path to aipcc-product-management-configs repo root
  --krd-repo      Path to a cloned konflux-release-data repo
  --product       Product directory to check (e.g. rhelai, rhaiis)
  --all           Check all products
  --help          Show this help

Examples:
  # Check a single product
  $(basename "$0") --configs-dir ../aipcc-product-management-configs --krd-repo ../konflux-release-data --product rhelai

  # Check all products
  $(basename "$0") --configs-dir ../aipcc-product-management-configs --krd-repo ../konflux-release-data --all
EOF
    exit "${1:-0}"
}

CONFIGS_DIR=""
KRD_REPO=""
PRODUCT=""
CHECK_ALL=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --configs-dir) CONFIGS_DIR="$2"; shift 2 ;;
        --krd-repo)    KRD_REPO="$2"; shift 2 ;;
        --product)     PRODUCT="$2"; shift 2 ;;
        --all)         CHECK_ALL=true; shift ;;
        --help)        usage 0 ;;
        *)             echo "Unknown option: $1"; usage 1 ;;
    esac
done

[[ -z "$CONFIGS_DIR" ]] && { echo "Error: --configs-dir is required"; usage 1; }
[[ -z "$KRD_REPO" ]]    && { echo "Error: --krd-repo is required"; usage 1; }
[[ -z "$PRODUCT" && "$CHECK_ALL" == "false" ]] && { echo "Error: --product or --all is required"; usage 1; }

CONFIGS_DIR="$(cd "$CONFIGS_DIR" && pwd)"
KRD_REPO="$(cd "$KRD_REPO" && pwd)"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PMT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ "$CHECK_ALL" == "true" ]]; then
    PRODUCTS=()
    for dir in "$CONFIGS_DIR"/*/; do
        name="$(basename "$dir")"
        [[ "$name" == .* ]] && continue
        [[ -d "$dir" ]] && PRODUCTS+=("$name")
    done
else
    PRODUCTS=("$PRODUCT")
fi

OVERALL_DRIFT=0

for product in "${PRODUCTS[@]}"; do
    product_dir="$CONFIGS_DIR/$product"
    if [[ ! -d "$product_dir" ]]; then
        echo "Warning: product directory not found: $product_dir — skipping"
        continue
    fi

    echo "=== Checking drift for: $product ==="

    # Reset KRD repo to clean state before each product
    git -C "$KRD_REPO" checkout -- . 2>/dev/null || true
    git -C "$KRD_REPO" clean -fd 2>/dev/null || true

    # Build config args: top-level YAML + branch-level config*.yaml (excludes releases/)
    CONFIG_ARGS=(--config "$product_dir/*.yaml" --config "$product_dir/*/config*.yaml")

    # Run PMT to generate expected KRD output into the cloned repo
    cd "$PMT_DIR"
    uv run python onboard-product.py \
        "${CONFIG_ARGS[@]}" \
        --mode krd \
        --krd-path "$KRD_REPO" \
        --recreate \
        --skip-repo-checks \
        2>&1 | sed 's/^/  /'

    # Check for drift
    cd "$KRD_REPO"
    DRIFT=0

    DIFF_OUTPUT="$(git diff --stat 2>&1)" || true
    UNTRACKED="$(git ls-files --others --exclude-standard 2>&1)" || true

    if [[ -n "$DIFF_OUTPUT" ]]; then
        echo ""
        echo "  DRIFT: modified/deleted files in $product"
        git diff --stat | sed 's/^/    /'
        echo ""
        git diff | sed 's/^/    /'
        DRIFT=1
    fi

    if [[ -n "$UNTRACKED" ]]; then
        echo ""
        echo "  DRIFT: files generated by PMT but missing from KRD ($product)"
        echo "$UNTRACKED" | sed 's/^/    /'
        DRIFT=1
    fi

    if [[ "$DRIFT" -eq 0 ]]; then
        echo "  No drift detected"
    else
        OVERALL_DRIFT=1
    fi

    echo ""
done

if [[ "$OVERALL_DRIFT" -eq 0 ]]; then
    echo "All products are in sync."
else
    echo "Drift detected — see above for details."
    exit 1
fi
